@startuml
' https://www.codeproject.com/Articles/1278703/UML-Made-Easy-with-PlantUML-VS-Code
' java -jar ~/.vscode/extensions/jebbs.plantuml-2.13.14/plantuml.jar -verbose *.plantuml ../out/index.plantuml
' https://plantuml.com/es/component-diagram
' https://plantuml.com/es/ie-diagram



' skinparam Style strictuml
skinparam SequenceMessageAlignment center
skinparam backgroundColor #FFFFFF
skinparam roundcorner 5
skinparam wrapWidth 400
skinparam wrapMessageWidth 400


PODS -up- Wordpress 
frame Wordpress {
    class Wp_Post <<Wp_Post>>{
        * post_id: number <<generated>>
        - post_title: string
        - post_date: Date
        - content: string
        + get_the_id()
        + get_the_title()
        + get_the_date()
        + get_the_content()
    }
}

' PODS -right- Amazon
frame Amazon {
    class AAWP_Template_Handler <<AAWP_Template_Handler>>{
        - asin
        ==
        + get_product_id()
        + get_template_variable(name, bool)
        + get_template_variables()
        + get_product_title()
        + get_product_url()
        + get_product_rating()
        + get_product_reviews()
    }
}

frame PODS {

    class Libro {
        - _source: Wp_Post
        * id: number
        - titulo: string
        - portada: binary
        - isbn:string
        - asin:string
        - autores: map
        - editorial: Editorial
        - fecha_publicacion: date
        - formato: map
        - formatos: map
        - sinopsis: string
        - paginas: number
        - idioma: enum
        - generos_literarios: Genero
        - estado: map
        - <b>descripcion: string</b>
        - notas: map
        - reviews: map
        - favorito: boolean
        - goodreads_url: string
        - series: map Serie
        - recomendaciones: map
        ==
        + get_titulo() 
        + get_reviews()
        + <b>get_rating()</b> 
    }

    Libro::_source ||-|| Wp_Post: contains 
    Libro::series }o-o{ Serie::libros contains

    enum idioma {
        ES
        EN
    }

    map formato {
        1 => Kindle
        2 => E-book
        3 => Paperback
        4 => Hardback
        5 => Audiobook
    }
    map estado {
        0 => Por leer
        1 => Siguiente
        2 => Leido
        3 => Leyendo
        4 => Cerrado
        5 => Pausado
        6 => No interesado
        7 => Cuarentena
    }
    
    class Review {
        - <b>contenido: string</b>
        - libro: Libro
        - rating: integer
        - goodreads_url: string
    }

    class Nota {
        - Libro: Libro
        - contenido:string
    }

    class Autor{
        - nombre: string
        - apellidos: string
        - portada: binary
        - libros: map
        - <b>contenido: string</b>
        - url: string
        - goodreads_url: string
    }

    class Editorial{
        - libros: map
        - <b>contenido: string</b>
        - url: string
    }

    class Recomendacion {
        - pregunta
        - autor_pregunta
        - respuesta
        - url:string
        - libros: map
    }

    class Serie {
        - libros: map
        - goodreads_url: string
    }

    class Foto{
        - portada: binary
        - fecha_captura: datetime
        - gps: double
        - <b>contenido: string</b>
        - instagram_url
        - googlemaps_url
    }

    class Generos{

    }
}

    PODS -right Amazon 
' Libro "1" o--|| "*" AAWP_Template_Handler: contains

note top of Libro 
    There are two types of 
    Libro: WP_POST and AAWP
end note
Libro ||--o{ Review
Libro ||--o{ Nota
Libro ||-down|{ Autor
Libro ||-down|| Editorial
Libro::estado -left|| estado : map
Libro::formato -left|| formato : map
Libro::idioma -left|| idioma : enum
Libro::generos_literarios ||-o{ Generos
Libro ||--o{ Recomendacion
Libro --[hidden] Foto



frame Goodreads {
    note top of Jei_Api_Goodreads 
        GOODREADS = GR
        goodreads.com/user_status/show/GR_USER_ID?format=xml&key=GR_KEY
        goodreads.com/review/show/2312483779
    end note
    class Jei_Api_Goodreads {
        + getAuthor(GR_AUTHOR_ID: integer)
        + getBook(GR_BOOK_ID: integer)
        + getLatestReads(GR_USER_ID: integer)
        + getUser(GR_USER_ID: integer)
        + getUserStatus(GR_USER_ID: integer)
        + getUserStatuses(GR_USER_ID: integer)
        + getReview(review_id: integer)
    }
}




Libro -right-> Goodreads 

    
@enduml