@startuml
actor User

box "Libro"

User --> Selected: DoSearch
activate Selected

Selected --> QuieroLeer: DoExpectativas
activate QuieroLeer
QuieroLeer -> QuieroLeer: SetNota/Lectura
activate QuieroLeer #DarkSalmon

end box

box "Nota/Lectura" 

QuieroLeer --> Leyendo: DoWait 
activate Leyendo 

Leyendo --> Leido: DoReading 
activate Leido
Leido -> Leido: SetNota 
activate Leido #DarkSalmon  

end box 

box "Review" 

Leido --> Reviewed: DoWait
activate Reviewed
Reviewed -> Reviewed : SetContenido 
activate Reviewed #DarkSalmon 

Reviewed --> Rated: DoRating
activate Rated

end box

Rated --> Reviewed: WorkDone
deactivate Rated
deactivate Reviewed
 
Reviewed --> Leido: WorkDone
destroy Reviewed
deactivate Leido 

Leido --> Leyendo: RequestCreated
deactivate Leido

Leyendo --> QuieroLeer: RequestCreated
deactivate Leyendo
deactivate QuieroLeer 

QuieroLeer --> Selected: Done
deactivate QuieroLeer

Selected --> User: Done
deactivate Selected
@enduml