GET http://192.168.1.47/jesuserro.com/wp-json/wp/v2/libro

###

GET http://192.168.1.47/jesuserro.com/wp-json

###

GET http://jesuserro.com/wp-json

###


GET https://www.googleapis.com/books/v1/volumes?q=isbn:9788428537698

###

GET https://www.goodreads.com/book/isbn?format=xml&key=DkLO3yfzNSM1JLOIJFXL3A&isbn=9788428537698

###

POST https://www.goodreads.com/book/isbn?format=xml&key=DkLO3yfzNSM1JLOIJFXL3A&isbn=9788428537698

###

POST https://www.googleapis.com/books/v1/volumes?q=isbn:9788428537698
Content-Type: application/json

{
    "title":"post de prueba",
    "body":"desc"
}